
@startuml

actor Пользователь as u
participant Приложение as p
participant БЭК as b
database "База данных" as d

u -> p: выбирает заметку
u <-- p: открывает заметку
u -> p: нажимает кнопку "Удалить"
u <-- p: выдаёт запрос 'Удалить заметку?"
u -> p: нажимает кнопку "Да!"
p -> b: отправляет запрос `DELETE http://notesapp.su/api//notes/{id}`
b -> d: удаляет заметку
b <-- d: заметка удалена
p <-- b: 204 "Заметка успешно удалена"
u <-- p: "Заметка успешно удалена!"

alt Пользователь открыл не ту заметку
u -> p: выбирает заметку
u <-- p: открывает заметку
u -> p: выбирает "Мои заметки"
u <-- p: открывает гланое окно приложения
end alt

alt Пользователь выбрал для удаления не ту заметку
u -> p: выбирает заметку
u <-- p: открывает заметку
u -> p: нажимает кнопку "Удалить"
u <-- p: выдаёт запрос "Удалить заметку?"
u -> p: нажимает кнопку "Нет!"
u <-- p: открывает заметку
end alt

@enduml

